version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    container_name:  elasticsearch
    ulimits: # overrides ulimits (defines amount of resources the user can open or use)
      memlock:
        soft: -1
        hard: -1
    environment: 
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node # by default elasticsearch expect a multi-node cluster
    volumes: 
      - ./elasticsearch/data/:/usr/share/elasticsearch/data
    ports: 
      - 9200:9200 # http
      - 9300:9300 # transport

  logstash:
    image: docker.elastic.co/logstash/logstash:7.11.0
    container_name: logstash
    volumes: 
      - ./logstash/pipeline/:/usr/share/logstash/pipeline
      - ./logs/:/usr/share/logstash/logs-test
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline/start.options:/usr/share/logstash/config/start.options
      - ./logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml
    ports:
      - 5044:5044
      - 9600:9600 # Logstash Api
    depends_on: 
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.0
    container_name: kibana
    ports:
      - 5601:5601
    depends_on: 
      - elasticsearch
